/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AppointmentDto } from './models/appointment-dto';
export type { ClientDto } from './models/client-dto';
export type { ClinicDto } from './models/clinic-dto';
export type { LoginDto } from './models/login-dto';
export type { RegisterDto } from './models/register-dto';
export type { RoomDto } from './models/room-dto';
export type { SessionDto } from './models/session-dto';
export type { UpdateUserDto } from './models/update-user-dto';
export type { UserDto } from './models/user-dto';
