/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentDto } from '../../models/appointment-dto';

export interface AppointmentsControllerFindAll$Params {
}

export function appointmentsControllerFindAll(http: HttpClient, rootUrl: string, params?: AppointmentsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentDto>>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppointmentDto>>;
    })
  );
}

appointmentsControllerFindAll.PATH = '/appointments';
