/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentDto } from '../../models/appointment-dto';

export interface AppointmentsControllerUpdate$Params {
  id: string;
}

export function appointmentsControllerUpdate(http: HttpClient, rootUrl: string, params: AppointmentsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentDto>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentDto>;
    })
  );
}

appointmentsControllerUpdate.PATH = '/appointments/{id}';
