/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentDto } from '../../models/appointment-dto';

export interface AppointmentsControllerCreate$Params {
      body: AppointmentDto
}

export function appointmentsControllerCreate(http: HttpClient, rootUrl: string, params: AppointmentsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentDto>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentDto>;
    })
  );
}

appointmentsControllerCreate.PATH = '/appointments';
