/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentDto } from '../../models/appointment-dto';

export interface AppointmentsControllerFindByClinic$Params {
  clinicId: string;
}

export function appointmentsControllerFindByClinic(http: HttpClient, rootUrl: string, params: AppointmentsControllerFindByClinic$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppointmentDto>>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerFindByClinic.PATH, 'get');
  if (params) {
    rb.path('clinicId', params.clinicId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppointmentDto>>;
    })
  );
}

appointmentsControllerFindByClinic.PATH = '/appointments/clinic/{clinicId}';
