/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentDto {
  clientId: string;
  clinicId: string;
  employeeId: string;
  endTime: string;
  id: string;
  roomId: string;
  startTime: string;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
}
