/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface ClientDto {
  '_id'?: string;
  address?: string;

  /**
   * The clinic ID this client belongs to
   */
  clinic: string;
  createdAt?: string;
  firstName: string;
  lastName: string;
  notes?: string;
  phone?: string;
  updatedAt?: string;

  /**
   * The email of the linked user account
   */
  userEmail?: UserDto;
}
