/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomDto } from '../models/room-dto';
import { UserDto } from '../models/user-dto';
export interface ClinicDto {
  address: string;
  adminIds: Array<string>;
  closingHours?: string;
  createdAt: string;
  email?: string;
  employeeIds?: Array<UserDto>;
  feesPercentage?: number;
  id?: string;
  logo?: string;
  name: string;
  openingHours?: string;
  phone?: string;
  rooms?: Array<RoomDto>;
  updatedAt: string;
  website?: string;
}
