/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {
  deviceType?: string;
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}
