/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoomDto {
  description?: string;

  /**
   * ID único de la sala
   */
  id: string;
  name: string;

  /**
   * URL de la imagen alojada en S3
   */
  photo: string;
}
