/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionDto {

  /**
   * Type of device connecting
   */
  deviceType: string;

  /**
   * Whether to remember the session (30 days) vs standard (7 days)
   */
  rememberMe?: boolean;

  /**
   * The user ID linking to the session
   */
  userId: string;
  _id: string;
  updatedAt: string;
}
