/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  '__v': number;
  '_id': string;
  createdAt: string;
  email: string;
  firstName: string;
  googleId: string;
  lastName: string;
  picture: string;
  updatedAt: string;
}
